packages:
  - apps/*
  - packages/*
  - functions
  - api

overrides:
  '@react-native-community/cli@<17.0.1': '>=17.0.1'
  esbuild@<=0.24.2: '>=0.25.0'
  send@<0.19.0: '>=0.19.0'
  tar@=7.5.1: '>=7.5.2'
  undici@>=6.0.0 <6.21.1: '>=6.21.1'
  undici@>=6.0.0 <6.21.2: '>=6.21.2'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
