import type { Questionnaire } from '../../types';

/**
 * Questionnaire Life Journey - 7 Sphères Vitales
 * Evaluation complète du mode de vie selon 6 dimensions clés
 * Remplace l'ancien questionnaire mode-de-vie
 */
export const life_journey: Questionnaire = {
  metadata: {
    id: 'life-journey',
    title: 'Mode de vie – 7 Sphères Vitales',
    category: 'mode-de-vie-siin',
    description:
      'Évaluez votre mode de vie selon 7 dimensions clés : sommeil, rythme, stress, activité physique, toxiques, relations sociales et alimentation',
    estimatedDuration: 20,
    version: '1.0',
    tags: ['life-journey', 'mode-de-vie', 'siin', 'radar', 'spheres-vitales'],
  },
  sections: [
    {
      id: 'physical',
      title: 'Sphère Physique',
      description: 'Évaluation de votre condition physique et de votre vitalité',
      questions: [
        {
          id: 'physical_energy',
          label: "Comment évaluez-vous votre niveau d'énergie physique au quotidien ?",
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Épuisé(e)',
            50: 'Modéré',
            100: "Débordant(e) d'énergie",
          },
        },
        {
          id: 'physical_activity',
          label:
            'Combien de fois par semaine pratiquez-vous une activité physique (minimum 30 min) ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais ou presque jamais', value: '0', points: 0 },
            { label: '1 fois par semaine', value: '1', points: 20 },
            { label: '2-3 fois par semaine', value: '2-3', points: 50 },
            { label: '4-5 fois par semaine', value: '4-5', points: 80 },
            { label: '5+ fois par semaine', value: '5+', points: 100 },
          ],
        },
        {
          id: 'physical_pain',
          label: 'À quelle fréquence ressentez-vous des douleurs physiques ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais', value: 'never', points: 100 },
            { label: 'Rarement (< 1 fois/mois)', value: 'rarely', points: 80 },
            { label: 'Parfois (1-2 fois/semaine)', value: 'sometimes', points: 50 },
            { label: 'Souvent (3-5 fois/semaine)', value: 'often', points: 20 },
            { label: 'Quotidiennement', value: 'daily', points: 0 },
          ],
        },
        {
          id: 'physical_sleep',
          label: 'Comment évaluez-vous la qualité de votre sommeil ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Très mauvais',
            50: 'Correct',
            100: 'Excellent',
          },
        },
        {
          id: 'physical_vitality',
          label: 'Le matin au réveil, comment vous sentez-vous ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Frais et reposé', value: 'fresh', points: 100 },
            { label: 'Assez reposé', value: 'rested', points: 75 },
            { label: 'Légèrement fatigué', value: 'slightly-tired', points: 50 },
            { label: 'Fatigué', value: 'tired', points: 25 },
            { label: 'Épuisé', value: 'exhausted', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'emotional',
      title: 'Sphère Émotionnelle',
      description: 'Évaluation de votre bien-être émotionnel et de votre humeur',
      questions: [
        {
          id: 'emotional_wellbeing',
          label: 'Comment décririez-vous votre bien-être émotionnel général ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Très mal',
            50: 'Ni bien ni mal',
            100: 'Excellent',
          },
        },
        {
          id: 'emotional_mood',
          label: 'Comment est votre humeur la plupart du temps ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Joyeux(se) et optimiste', value: 'joyful', points: 100 },
            { label: 'Plutôt positif(ve)', value: 'positive', points: 75 },
            { label: 'Variable', value: 'variable', points: 50 },
            { label: 'Plutôt négatif(ve)', value: 'negative', points: 25 },
            { label: 'Triste ou déprimé(e)', value: 'sad', points: 0 },
          ],
        },
        {
          id: 'emotional_stress',
          label: 'À quelle fréquence vous sentez-vous stressé(e) ou anxieux(se) ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais ou rarement', value: 'never', points: 100 },
            { label: 'Parfois', value: 'sometimes', points: 75 },
            { label: 'Souvent', value: 'often', points: 40 },
            { label: 'Très souvent', value: 'very-often', points: 15 },
            { label: 'En permanence', value: 'always', points: 0 },
          ],
        },
        {
          id: 'emotional_expression',
          label: "Êtes-vous à l'aise pour exprimer vos émotions ?",
          type: 'select',
          required: true,
          options: [
            { label: "Très à l'aise", value: 'very-comfortable', points: 100 },
            { label: "À l'aise", value: 'comfortable', points: 75 },
            { label: "Moyennement à l'aise", value: 'somewhat', points: 50 },
            { label: "Peu à l'aise", value: 'uncomfortable', points: 25 },
            { label: "Pas du tout à l'aise", value: 'not-at-all', points: 0 },
          ],
        },
        {
          id: 'emotional_resilience',
          label: "Comment vous remettez-vous d'événements émotionnellement difficiles ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Très rapidement (quelques heures)', value: 'very-fast', points: 100 },
            { label: 'Rapidement (1-2 jours)', value: 'fast', points: 75 },
            { label: 'Normalement (quelques jours)', value: 'normal', points: 50 },
            { label: 'Lentement (plusieurs semaines)', value: 'slow', points: 25 },
            { label: 'Très lentement (plusieurs mois)', value: 'very-slow', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'mental',
      title: 'Sphère Mentale',
      description: 'Évaluation de votre clarté mentale et de vos capacités cognitives',
      questions: [
        {
          id: 'mental_clarity',
          label: 'Comment évaluez-vous votre clarté mentale au quotidien ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Très confus',
            50: 'Variable',
            100: 'Très clair',
          },
        },
        {
          id: 'mental_concentration',
          label: 'Comment est votre capacité de concentration ?',
          type: 'select',
          required: true,
          options: [
            {
              label: 'Excellente (concentration prolongée facile)',
              value: 'excellent',
              points: 100,
            },
            { label: 'Bonne', value: 'good', points: 75 },
            { label: 'Moyenne (distraction occasionnelle)', value: 'average', points: 50 },
            { label: 'Faible (distraction fréquente)', value: 'poor', points: 25 },
            { label: 'Très faible (impossible de me concentrer)', value: 'very-poor', points: 0 },
          ],
        },
        {
          id: 'mental_memory',
          label: 'Comment évaluez-vous votre mémoire ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Excellente', value: 'excellent', points: 100 },
            { label: 'Bonne', value: 'good', points: 75 },
            { label: 'Moyenne (oublis occasionnels)', value: 'average', points: 50 },
            { label: 'Faible (oublis fréquents)', value: 'poor', points: 25 },
            { label: 'Très faible (oublis constants)', value: 'very-poor', points: 0 },
          ],
        },
        {
          id: 'mental_learning',
          label: 'Avec quelle facilité apprenez-vous de nouvelles choses ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Très facilement', value: 'very-easy', points: 100 },
            { label: 'Facilement', value: 'easy', points: 75 },
            { label: 'Moyennement', value: 'average', points: 50 },
            { label: 'Difficilement', value: 'difficult', points: 25 },
            { label: 'Très difficilement', value: 'very-difficult', points: 0 },
          ],
        },
        {
          id: 'mental_creativity',
          label: 'Vous sentez-vous créatif(ve) et capable de résoudre des problèmes ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Pas du tout',
            50: 'Moyennement',
            100: 'Très créatif(ve)',
          },
        },
      ],
    },
    {
      id: 'social',
      title: 'Sphère Sociale',
      description: 'Évaluation de vos relations et de votre vie sociale',
      questions: [
        {
          id: 'social_relationships',
          label: 'Comment évaluez-vous la qualité de vos relations sociales ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Très mauvaises',
            50: 'Correctes',
            100: 'Excellentes',
          },
        },
        {
          id: 'social_support',
          label: 'Avez-vous des personnes sur qui compter en cas de besoin ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Oui, plusieurs personnes', value: 'many', points: 100 },
            { label: 'Oui, quelques personnes', value: 'some', points: 75 },
            { label: 'Oui, une ou deux personnes', value: 'few', points: 50 },
            { label: 'Peut-être une personne', value: 'maybe-one', points: 25 },
            { label: 'Non, personne', value: 'none', points: 0 },
          ],
        },
        {
          id: 'social_frequency',
          label: 'À quelle fréquence avez-vous des interactions sociales significatives ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Quotidiennement', value: 'daily', points: 100 },
            { label: 'Plusieurs fois par semaine', value: 'several-week', points: 75 },
            { label: 'Une fois par semaine', value: 'weekly', points: 50 },
            { label: 'Quelques fois par mois', value: 'monthly', points: 25 },
            { label: 'Rarement ou jamais', value: 'rarely', points: 0 },
          ],
        },
        {
          id: 'social_belonging',
          label: 'Vous sentez-vous appartenir à une communauté ou un groupe ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Oui, fortement', value: 'strongly', points: 100 },
            { label: 'Oui, modérément', value: 'moderately', points: 75 },
            { label: 'Un peu', value: 'somewhat', points: 50 },
            { label: 'Très peu', value: 'little', points: 25 },
            { label: 'Pas du tout', value: 'not-at-all', points: 0 },
          ],
        },
        {
          id: 'social_communication',
          label: 'Comment évaluez-vous votre capacité à communiquer avec les autres ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Très difficile',
            50: 'Moyenne',
            100: 'Très facile',
          },
        },
      ],
    },
    {
      id: 'spiritual',
      title: 'Sphère Spirituelle',
      description: 'Évaluation de votre sens et de votre alignement avec vos valeurs',
      questions: [
        {
          id: 'spiritual_meaning',
          label: 'Trouvez-vous du sens et un but à votre vie ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Aucun sens',
            50: 'Un peu de sens',
            100: 'Sens profond',
          },
        },
        {
          id: 'spiritual_values',
          label: 'Vivez-vous en accord avec vos valeurs personnelles ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Totalement en accord', value: 'fully-aligned', points: 100 },
            { label: 'Largement en accord', value: 'mostly-aligned', points: 75 },
            { label: 'Partiellement en accord', value: 'partially-aligned', points: 50 },
            { label: 'Peu en accord', value: 'little-aligned', points: 25 },
            { label: 'Pas du tout en accord', value: 'not-aligned', points: 0 },
          ],
        },
        {
          id: 'spiritual_practice',
          label: 'Avez-vous une pratique spirituelle, méditative ou contemplative ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Oui, quotidienne', value: 'daily', points: 100 },
            { label: 'Oui, plusieurs fois par semaine', value: 'several-week', points: 75 },
            { label: 'Oui, occasionnelle', value: 'occasional', points: 50 },
            { label: 'Rare', value: 'rare', points: 25 },
            { label: 'Non', value: 'none', points: 0 },
          ],
        },
        {
          id: 'spiritual_gratitude',
          label: 'Ressentez-vous de la gratitude dans votre vie quotidienne ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Quotidiennement', value: 'daily', points: 100 },
            { label: 'Souvent', value: 'often', points: 75 },
            { label: 'Parfois', value: 'sometimes', points: 50 },
            { label: 'Rarement', value: 'rarely', points: 25 },
            { label: 'Jamais', value: 'never', points: 0 },
          ],
        },
        {
          id: 'spiritual_connection',
          label: 'Vous sentez-vous connecté(e) à quelque chose de plus grand que vous ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Pas du tout',
            50: 'Moyennement',
            100: 'Très connecté(e)',
          },
        },
      ],
    },
    {
      id: 'environmental',
      title: 'Sphère Environnementale',
      description: 'Évaluation de votre environnement de vie et de travail',
      questions: [
        {
          id: 'environmental_home',
          label:
            'Comment évaluez-vous la qualité de votre environnement de vie (maison, appartement) ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Très insatisfaisant',
            50: 'Correct',
            100: 'Excellent',
          },
        },
        {
          id: 'environmental_work',
          label: 'Comment évaluez-vous la qualité de votre environnement de travail ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Excellent', value: 'excellent', points: 100 },
            { label: 'Bon', value: 'good', points: 75 },
            { label: 'Correct', value: 'average', points: 50 },
            { label: 'Médiocre', value: 'poor', points: 25 },
            { label: 'Très mauvais ou sans emploi', value: 'very-poor', points: 0 },
          ],
        },
        {
          id: 'environmental_nature',
          label: 'Combien de temps passez-vous dans la nature chaque semaine ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Plus de 5 heures', value: 'more-5h', points: 100 },
            { label: '3-5 heures', value: '3-5h', points: 75 },
            { label: '1-3 heures', value: '1-3h', points: 50 },
            { label: "Moins d'1 heure", value: 'less-1h', points: 25 },
            { label: 'Jamais ou presque', value: 'never', points: 0 },
          ],
        },
        {
          id: 'environmental_pollution',
          label: 'Comment évaluez-vous votre exposition à la pollution (air, bruit, etc.) ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Très faible', value: 'very-low', points: 100 },
            { label: 'Faible', value: 'low', points: 75 },
            { label: 'Modérée', value: 'moderate', points: 50 },
            { label: 'Élevée', value: 'high', points: 25 },
            { label: 'Très élevée', value: 'very-high', points: 0 },
          ],
        },
        {
          id: 'environmental_safety',
          label: 'Vous sentez-vous en sécurité dans votre environnement quotidien ?',
          type: 'slider',
          required: true,
          min: 0,
          max: 100,
          step: 5,
          defaultValue: 50,
          labels: {
            0: 'Pas du tout en sécurité',
            50: 'Moyennement',
            100: 'Totalement en sécurité',
          },
        },
      ],
    },
  ],
};
