import type { Questionnaire } from '../../types';

export const mode_de_vie: Questionnaire = {
  metadata: {
    id: 'mode-de-vie',
    title: 'Questionnaire Mode de Vie',
    category: 'mode-de-vie',
    description:
      'Évaluation complète de votre mode de vie : sommeil, rythme biologique, stress, activité physique, exposition aux toxiques, relations et alimentation',
    estimatedDuration: 15,
    version: '1.0',
    tags: ['mode-de-vie', 'sommeil', 'stress', 'nutrition', 'activité-physique'],
  },
  sections: [
    {
      id: 'sommeil',
      title: 'Votre sommeil',
      description: 'Évaluation de la qualité et de la quantité de votre sommeil',
      questions: [
        {
          id: 'qualite_sommeil',
          label: 'Comment évaluez-vous la qualité de votre sommeil ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Je dors très bien', value: 'tres-bien', points: 10 },
            { label: 'Je dors bien', value: 'bien', points: 8 },
            { label: 'Je dors moyennement', value: 'moyen', points: 5 },
            { label: 'Je dors mal', value: 'mal', points: 2 },
            { label: 'Je dors très mal', value: 'tres-mal', points: 0 },
          ],
        },
        {
          id: 'duree_sommeil',
          label: "Combien d'heures dormez-vous par nuit en moyenne ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Plus de 8h par nuit', value: 'plus-8h', points: 10 },
            { label: '7-8h par nuit', value: '7-8h', points: 8 },
            { label: '6-7h par nuit', value: '6-7h', points: 5 },
            { label: '5-6h par nuit', value: '5-6h', points: 2 },
            { label: 'Moins de 5h par nuit', value: 'moins-5h', points: 0 },
          ],
        },
        {
          id: 'endormissement',
          label: 'Combien de temps mettez-vous pour vous endormir ?',
          type: 'select',
          required: true,
          options: [
            { label: "Je m'endors facilement (< 15 min)", value: 'moins-15min', points: 10 },
            { label: "Je m'endors assez facilement (15-30 min)", value: '15-30min', points: 7 },
            {
              label: "J'ai des difficultés d'endormissement (30-60 min)",
              value: '30-60min',
              points: 3,
            },
            { label: "J'ai beaucoup de difficultés (> 60 min)", value: 'plus-60min', points: 0 },
          ],
        },
        {
          id: 'reveils_nocturnes',
          label: 'À quelle fréquence vous réveillez-vous la nuit ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais ou rarement', value: 'jamais-rarement', points: 10 },
            { label: 'Parfois (1-2 fois par semaine)', value: 'parfois', points: 7 },
            { label: 'Souvent (3-5 fois par semaine)', value: 'souvent', points: 3 },
            { label: 'Toutes les nuits', value: 'toutes-nuits', points: 0 },
          ],
        },
        {
          id: 'reveil_matinal',
          label: 'Comment vous sentez-vous au réveil ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Je me réveille frais et reposé', value: 'frais-repose', points: 10 },
            { label: 'Je me réveille assez reposé', value: 'assez-repose', points: 7 },
            { label: 'Je me réveille fatigué', value: 'fatigue', points: 3 },
            { label: 'Je me réveille très fatigué', value: 'tres-fatigue', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'rythme-biologique',
      title: 'Votre rythme biologique',
      description: 'Évaluation de la régularité de vos rythmes quotidiens',
      questions: [
        {
          id: 'horaires_coucher',
          label: 'Vos horaires de coucher sont-ils réguliers ?',
          type: 'select',
          required: true,
          options: [
            {
              label: 'Réguliers (tous les jours à la même heure ±30min)',
              value: 'reguliers',
              points: 10,
            },
            { label: 'Assez réguliers (±1h)', value: 'assez-reguliers', points: 7 },
            { label: 'Irréguliers (±2h)', value: 'irreguliers', points: 3 },
            { label: 'Très irréguliers (> 2h de variation)', value: 'tres-irreguliers', points: 0 },
          ],
        },
        {
          id: 'horaires_lever',
          label: 'Vos horaires de lever sont-ils réguliers ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Réguliers (tous les jours ±30min)', value: 'reguliers', points: 10 },
            { label: 'Assez réguliers (±1h)', value: 'assez-reguliers', points: 7 },
            { label: 'Irréguliers (±2h)', value: 'irreguliers', points: 3 },
            { label: 'Très irréguliers (> 2h)', value: 'tres-irreguliers', points: 0 },
          ],
        },
        {
          id: 'exposition_lumiere',
          label: "Combien de temps passez-vous à l'extérieur en lumière naturelle ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Plus de 2h par jour en extérieur', value: 'plus-2h', points: 10 },
            { label: '1-2h par jour', value: '1-2h', points: 7 },
            { label: '30min-1h par jour', value: '30min-1h', points: 3 },
            { label: 'Moins de 30min par jour', value: 'moins-30min', points: 0 },
          ],
        },
        {
          id: 'ecrans_soir',
          label: "Jusqu'à quelle heure utilisez-vous des écrans le soir ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais après 20h', value: 'jamais-apres-20h', points: 10 },
            { label: "Rarement (jusqu'à 21h)", value: 'jusqua-21h', points: 7 },
            { label: "Souvent (jusqu'à 22h)", value: 'jusqua-22h', points: 3 },
            { label: 'Très souvent (après 22h)', value: 'apres-22h', points: 0 },
          ],
        },
        {
          id: 'heure_repas_soir',
          label: 'À quelle heure prenez-vous votre repas du soir ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Avant 19h30', value: 'avant-19h30', points: 10 },
            { label: 'Entre 19h30 et 20h30', value: '19h30-20h30', points: 7 },
            { label: 'Entre 20h30 et 21h30', value: '20h30-21h30', points: 3 },
            { label: 'Après 21h30', value: 'apres-21h30', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'stress',
      title: 'Votre adaptation et le stress',
      description: 'Évaluation de votre niveau de stress et de votre capacité à le gérer',
      questions: [
        {
          id: 'niveau_stress',
          label: 'Quel est votre niveau de stress ressenti au quotidien ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Très faible ou absent', value: 'tres-faible', points: 10 },
            { label: 'Faible', value: 'faible', points: 7 },
            { label: 'Modéré', value: 'modere', points: 5 },
            { label: 'Élevé', value: 'eleve', points: 2 },
            { label: 'Très élevé', value: 'tres-eleve', points: 0 },
          ],
        },
        {
          id: 'gestion_stress',
          label: 'Comment gérez-vous le stress ?',
          type: 'select',
          required: true,
          options: [
            {
              label: 'Très bonne (techniques de relaxation régulières)',
              value: 'tres-bonne',
              points: 10,
            },
            { label: 'Bonne (je gère bien)', value: 'bonne', points: 7 },
            { label: 'Moyenne (difficultés occasionnelles)', value: 'moyenne', points: 3 },
            { label: 'Mauvaise (je suis souvent dépassé)', value: 'mauvaise', points: 0 },
          ],
        },
        {
          id: 'anxiete',
          label: "À quelle fréquence ressentez-vous de l'anxiété ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais ou rarement anxieux', value: 'jamais-rarement', points: 10 },
            { label: 'Parfois anxieux', value: 'parfois', points: 7 },
            { label: 'Souvent anxieux', value: 'souvent', points: 3 },
            { label: 'Toujours ou presque toujours anxieux', value: 'toujours', points: 0 },
          ],
        },
        {
          id: 'situations_stressantes',
          label: 'À quelle fréquence vivez-vous des situations stressantes ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Rares (< 1 fois par semaine)', value: 'rares', points: 10 },
            { label: 'Occasionnelles (1-2 fois par semaine)', value: 'occasionnelles', points: 7 },
            { label: 'Fréquentes (3-5 fois par semaine)', value: 'frequentes', points: 3 },
            { label: 'Quotidiennes ou plus', value: 'quotidiennes', points: 0 },
          ],
        },
        {
          id: 'recuperation_stress',
          label: 'Combien de temps vous faut-il pour récupérer après un événement stressant ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Rapide (< 1h)', value: 'rapide', points: 10 },
            { label: 'Moyenne (1-3h)', value: 'moyenne', points: 7 },
            { label: 'Lente (plusieurs heures)', value: 'lente', points: 3 },
            { label: 'Très lente (plusieurs jours)', value: 'tres-lente', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'activite-physique',
      title: 'Votre activité physique',
      description: "Évaluation de votre niveau d'activité physique quotidien",
      questions: [
        {
          id: 'frequence_activite',
          label: 'À quelle fréquence pratiquez-vous une activité physique ?',
          type: 'select',
          required: true,
          options: [
            { label: '5 fois ou plus par semaine', value: '5-fois-plus', points: 10 },
            { label: '3-4 fois par semaine', value: '3-4-fois', points: 7 },
            { label: '1-2 fois par semaine', value: '1-2-fois', points: 3 },
            { label: 'Jamais ou presque jamais', value: 'jamais', points: 0 },
          ],
        },
        {
          id: 'duree_activite',
          label: "Quelle est la durée moyenne de vos séances d'activité physique ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Plus de 60 minutes', value: 'plus-60min', points: 10 },
            { label: '30-60 minutes', value: '30-60min', points: 7 },
            { label: '15-30 minutes', value: '15-30min', points: 3 },
            { label: 'Moins de 15 minutes', value: 'moins-15min', points: 0 },
          ],
        },
        {
          id: 'intensite_effort',
          label: "Quelle est l'intensité de vos efforts physiques ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Intensive (essoufflement, transpiration)', value: 'intensive', points: 10 },
            { label: 'Modérée (effort soutenu)', value: 'moderee', points: 7 },
            { label: 'Légère (marche tranquille)', value: 'legere', points: 3 },
            { label: 'Très légère', value: 'tres-legere', points: 0 },
          ],
        },
        {
          id: 'activite_quotidienne',
          label: "Quel est votre niveau d'activité quotidien (nombre de pas) ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Très actif (> 10000 pas/jour)', value: 'tres-actif', points: 10 },
            { label: 'Actif (7000-10000 pas/jour)', value: 'actif', points: 7 },
            { label: 'Peu actif (5000-7000 pas/jour)', value: 'peu-actif', points: 3 },
            { label: 'Sédentaire (< 5000 pas/jour)', value: 'sedentaire', points: 0 },
          ],
        },
        {
          id: 'position_assise',
          label: 'Combien de temps passez-vous assis(e) par jour ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Moins de 4h par jour', value: 'moins-4h', points: 10 },
            { label: '4-6h par jour', value: '4-6h', points: 7 },
            { label: '6-8h par jour', value: '6-8h', points: 3 },
            { label: 'Plus de 8h par jour', value: 'plus-8h', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'toxiques',
      title: 'Votre exposition aux toxiques',
      description: 'Évaluation de votre exposition aux substances toxiques',
      questions: [
        {
          id: 'tabac',
          label: 'Quelle est votre consommation de tabac ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Non-fumeur', value: 'non-fumeur', points: 10 },
            { label: 'Ex-fumeur (> 1 an)', value: 'ex-fumeur', points: 7 },
            { label: 'Fumeur occasionnel (< 5 cig/jour)', value: 'occasionnel', points: 2 },
            { label: 'Fumeur régulier (≥ 5 cig/jour)', value: 'regulier', points: 0 },
          ],
        },
        {
          id: 'alcool',
          label: "Quelle est votre consommation d'alcool par semaine ?",
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais ou très occasionnel', value: 'jamais-occasionnel', points: 10 },
            { label: 'Modéré (1-2 verres/semaine)', value: 'modere', points: 7 },
            { label: 'Régulier (3-7 verres/semaine)', value: 'regulier', points: 3 },
            { label: 'Important (> 7 verres/semaine)', value: 'important', points: 0 },
          ],
        },
        {
          id: 'exposition_professionnelle',
          label: 'Êtes-vous exposé(e) à des toxiques dans votre environnement professionnel ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Aucune exposition', value: 'aucune', points: 10 },
            { label: 'Exposition faible', value: 'faible', points: 7 },
            { label: 'Exposition modérée', value: 'moderee', points: 3 },
            {
              label: 'Exposition importante (produits chimiques, pesticides...)',
              value: 'importante',
              points: 0,
            },
          ],
        },
        {
          id: 'produits_menagers',
          label: 'Quels types de produits ménagers utilisez-vous ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Produits naturels/bio uniquement', value: 'naturels', points: 10 },
            { label: 'Mélange naturel et conventionnel', value: 'melange', points: 7 },
            { label: 'Produits conventionnels', value: 'conventionnels', points: 3 },
            { label: 'Produits chimiques puissants', value: 'chimiques', points: 0 },
          ],
        },
        {
          id: 'pollution_air',
          label: 'Dans quel environnement vivez-vous ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Campagne/air pur', value: 'campagne', points: 10 },
            { label: 'Petite ville', value: 'petite-ville', points: 7 },
            { label: 'Grande ville', value: 'grande-ville', points: 3 },
            { label: 'Zone très polluée/industrielle', value: 'polluee', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'relations',
      title: 'Votre relation aux autres',
      description: 'Évaluation de votre vie sociale et de vos relations',
      questions: [
        {
          id: 'vie_sociale',
          label: 'Comment évaluez-vous votre vie sociale ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Très riche (sorties/activités régulières)', value: 'tres-riche', points: 10 },
            { label: 'Riche (plusieurs fois par semaine)', value: 'riche', points: 7 },
            { label: 'Modérée (1 fois par semaine)', value: 'moderee', points: 3 },
            { label: 'Pauvre ou isolement', value: 'pauvre', points: 0 },
          ],
        },
        {
          id: 'qualite_relations',
          label: 'Comment évaluez-vous la qualité de vos relations ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Excellentes relations (soutien, écoute)', value: 'excellentes', points: 10 },
            { label: 'Bonnes relations', value: 'bonnes', points: 7 },
            { label: 'Relations moyennes (quelques conflits)', value: 'moyennes', points: 3 },
            { label: 'Relations difficiles (conflits fréquents)', value: 'difficiles', points: 0 },
          ],
        },
        {
          id: 'vie_couple_famille',
          label: 'Comment évaluez-vous votre vie de couple/famille ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Très épanouissante', value: 'tres-epanouissante', points: 10 },
            { label: 'Épanouissante', value: 'epanouissante', points: 7 },
            { label: 'Correcte', value: 'correcte', points: 3 },
            { label: 'Difficile ou seul(e)', value: 'difficile', points: 0 },
          ],
        },
        {
          id: 'activites_sociales',
          label: 'Participez-vous à des activités sociales (associations, clubs, bénévolat) ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Associations, clubs, bénévolat régulier', value: 'regulier', points: 10 },
            { label: 'Activités occasionnelles', value: 'occasionnelles', points: 7 },
            { label: 'Rares activités sociales', value: 'rares', points: 3 },
            { label: 'Aucune activité sociale', value: 'aucune', points: 0 },
          ],
        },
        {
          id: 'communication',
          label: 'Comment communiquez-vous avec les autres ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Je communique facilement et ouvertement', value: 'facilement', points: 10 },
            { label: 'Je communique assez bien', value: 'assez-bien', points: 7 },
            { label: "J'ai des difficultés à communiquer", value: 'difficultes', points: 3 },
            { label: 'Je ne communique pas ou très peu', value: 'pas-ou-peu', points: 0 },
          ],
        },
      ],
    },
    {
      id: 'alimentation',
      title: 'Votre mode alimentaire',
      description: 'Évaluation de vos habitudes alimentaires',
      questions: [
        {
          id: 'regularite_repas',
          label: 'Quelle est la régularité de vos repas ?',
          type: 'select',
          required: true,
          options: [
            { label: '3 repas réguliers par jour', value: '3-repas-reguliers', points: 10 },
            { label: '3 repas avec horaires variables', value: '3-repas-variables', points: 7 },
            { label: '2 repas par jour', value: '2-repas', points: 3 },
            { label: 'Repas irréguliers ou grignotage', value: 'irreguliers', points: 0 },
          ],
        },
        {
          id: 'petit_dejeuner',
          label: 'Prenez-vous un petit-déjeuner ?',
          type: 'select',
          required: true,
          options: [
            {
              label: 'Complet et équilibré tous les jours',
              value: 'complet-equilibre',
              points: 10,
            },
            { label: 'Complet la plupart du temps', value: 'complet-souvent', points: 7 },
            { label: 'Léger ou occasionnel', value: 'leger-occasionnel', points: 3 },
            { label: 'Pas de petit-déjeuner', value: 'pas-petit-dej', points: 0 },
          ],
        },
        {
          id: 'cuisine_maison',
          label: 'À quelle fréquence cuisinez-vous vous-même vos repas ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Tous les jours', value: 'tous-jours', points: 10 },
            { label: '5-6 fois par semaine', value: '5-6-fois', points: 7 },
            { label: '2-4 fois par semaine', value: '2-4-fois', points: 3 },
            { label: 'Rarement ou jamais', value: 'rarement-jamais', points: 0 },
          ],
        },
        {
          id: 'produits_frais',
          label: 'Consommez-vous des produits frais et de saison ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Toujours ou presque', value: 'toujours-presque', points: 10 },
            { label: 'Souvent', value: 'souvent', points: 7 },
            { label: 'Parfois', value: 'parfois', points: 3 },
            { label: 'Rarement', value: 'rarement', points: 0 },
          ],
        },
        {
          id: 'grignotage',
          label: 'À quelle fréquence grignotez-vous entre les repas ?',
          type: 'select',
          required: true,
          options: [
            { label: 'Jamais', value: 'jamais', points: 10 },
            { label: 'Rarement (< 1 fois/semaine)', value: 'rarement', points: 7 },
            { label: 'Occasionnel (2-3 fois/semaine)', value: 'occasionnel', points: 3 },
            { label: 'Fréquent (quotidien)', value: 'frequent', points: 0 },
          ],
        },
      ],
    },
  ],
};
